### ISSUE TITLE
Independence status

### ISSUE THREAD

**Issue by Crissov** [srcagency/iso-3166-1-codes#1]
I needed the list recently as well, but also the status of the `independent` attribute, so I made these:

- https://github.com/Crissov/unicode-proposals/blob/master/references/ISO_3166-1.tsv
- https://github.com/Crissov/unicode-proposals/blob/master/references/ISO_3166-1.md

I gathered the data half-manually directly from [ISO OBP](https://www.iso.org/obp/ui#search), so do not copy it blindly &ndash; some (maybe 1 to 3) yesses may in fact be nos, but I am pretty sure I did not add a no that should be a yes. Do not rely on [Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes) either, because I added the column to the table there, too. 

Unicode [mostly follows ISO](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Imperfect_implementations) for [CLDR](http://unicode.org/repos/cldr/tags/latest/common/validity/region.xml), but has a handful of additional entries (exceptionally reserved `AC`, `CP`, `DG`, `EA`, `IC` and `TA`, and user-assigned `XK` for Kosovo) and less [removed or deprecated entries](https://gist.github.com/Crissov/cc8880a922bc579b81c576e7f5c418ce), because it started life about two decades after ISO 3166 (which builds upon UN M.49, another three decades older). IANA also has some deviation for ccTLDs, notablz `.uk`  instead of `.gb`. It may be nice to provide diff sets or alternate tables here. 

Anyhow, for alpha-2 codes there is not much competition to ISO (perhaps [NATO](https://en.wikipedia.org/wiki/List_of_NATO_country_codes)), but alpha-3 codes are defined by [different standards](https://en.wikipedia.org/wiki/Comparison_of_alphabetic_country_codes) as well, with some incompatibilities.

There is, of course, also Part 2 of the standard with its [currently ca. 5000 codes](http://pastebin.com/raw/PKvWPeCj), as well as various reserved, deprecated or removed code elements.  It is in [beta stage](http://unicode.org/reports/tr51/proposed.html#flag-emoji-tag-sequences) for becoming the way to encode the British home nations for emoji flags etc.

**Comment by ramzi198563** [comment]
مرحبا 

بدى اتسعدنى فى استخراج بوابه cvv

**Comment by tjconcept** [comment]
Please see this section for my thoughts on extending the data: https://github.com/srcagency/iso-3166-1-codes#rationale.

Otherwise, I welcome extensions as separate packages and would gladly link to them from here.
